### ISSUE TITLE
VS IDE / option / environment / CLEAN SOLUTION

### ISSUE THREAD

**Issue by febitanya** [madskristensen/CloseAllTabs#10] opened 2018-09-25 13:11 UTC
### Installed product versions
- Visual Studio: 2017
- This extension: 1.4.28

ErrorS On:
* On IDE Loading Giving error ; The 'CleanOnClosePackage' package did not load correctly. 
* VS IDE / option / environment / CLEAN SOLUTION : An error occurred loading this property page

Whats may be wrong ?
BR

**Comment by madskristensen** [comment] 2018-09-25 16:24
Dupe of #9 

Fixed in latest release

**Closed as completed by madskristensen** 2018-09-25 16:24 UTC
